package xyz.almia.itemsystem;

public enum Enchantments {
	
	LIFESTEAL, JUMP, SPEED, SOULSHOT, BAT_VISION, ASSASSIN, VOLLEY, SNARE, AEGIS, WILD_MARK,
	HOLY_SMITE, DEMON_SIPHON, BLOODTHIRST, PETRIFY, EYEPATCH, SWIPE, PROTECTION, SHARPENED, FLAME;
	
}
