package xyz.almia.utils;

public enum Swears {
	
	FUCK, BITCH, NIGGER, CUNT, CLIT, DICK, COCK, SLUT, WHORE, MOTHERFUCKER, FUCKER, ASSHOLE, ASS, CHINK, FAGGOT, PRICK, FAG, RETARD,
	ASSFACE, ASSFUCK, GAY, ANUS, ASSHAT, ASSNIGGER, BASTARD, BULLOKS, DICKHEAD, KYS, CANCER, HOMO, IDIOT, JACKASS, PORN, SHITHEAD,
	SONOFABITCH, XXX, PUSSY, SHIT, PISS, HORNY, BLOWJOB, SEX, HITLER, VAGINA, DOUCHE, WANKER, QUEER, SCREW, STUPID;
	
}
